// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.0'
        classpath 'androidx.navigation:navigation-safe-args-gradle-plugin:2.7.7'
        classpath 'de.undercouch:gradle-download-task:4.1.2'
    }
}
// No build.gradle (Project: TFLite_Image_Classification)
plugins {
    // Mude a versão de 1.6.x para 1.8.10
    id 'org.jetbrains.kotlin.android' version '1.8.10' apply false

}

task clean(type: Delete) {
    delete rootProject.buildDir
}